export default [
    { value: "", displayValue: "Seleccionar" },
    { value: "Afganistán", displayValue: "Afganistán" },
    { value: "Albania", displayValue: "Albania" },
    { value: "Alemania", displayValue: "Alemania" },
    { value: "Andorra", displayValue: "Andorra" },
    { value: "Angola", displayValue: "Angola" },
    { value: "Anguilla", displayValue: "Anguilla" },
    { value: "Antártida", displayValue: "Antártida" },
    { value: "Antigua y Barbuda", displayValue: "Antigua y Barbuda" },
    { value: "Antillas Holandesas", displayValue: "Antillas Holandesas" },
    { value: "Arabia Saudí", displayValue: "Arabia Saudí" },
    { value: "Argelia", displayValue: "Argelia" },
    { value: "Argentina", displayValue: "Argentina" },
    { value: "Armenia", displayValue: "Armenia" },
    { value: "AW", displayValue: "Aruba" },
    { value: "Aruba", displayValue: "Australia" },
    { value: "Austria", displayValue: "Austria" },
    { value: "Azerbaiyán", displayValue: "Azerbaiyán" },
    { value: "Bahamas", displayValue: "Bahamas" },
    { value: "Bahrein", displayValue: "Bahrein" },
    { value: "Bangladesh", displayValue: "Bangladesh" },
    { value: "BB", displayValue: "Barbados" },
    { value: "Barbados", displayValue: "Bélgica" },
    { value: "Belice", displayValue: "Belice" },
    { value: "Benin", displayValue: "Benin" },
    { value: "Bermudas", displayValue: "Bermudas" },
    { value: "Bielorrusia", displayValue: "Bielorrusia" },
    { value: "Birmania", displayValue: "Birmania" },
    { value: "Bolivia", displayValue: "Bolivia" },
    { value: "Bosnia y Herzegovina", displayValue: "Bosnia y Herzegovina" },
    { value: "Botswana", displayValue: "Botswana" },
    { value: "Brasil", displayValue: "Brasil" },
    { value: "Brunei", displayValue: "Brunei" },
    { value: "Bulgaria", displayValue: "Bulgaria" },
    { value: "Burkina Faso", displayValue: "Burkina Faso" },
    { value: "Burundi", displayValue: "Burundi" },
    { value: "Bután", displayValue: "Bután" },
    { value: "Cabo Verde", displayValue: "Cabo Verde" },
    { value: "Camboya", displayValue: "Camboya" },
    { value: "Camerún", displayValue: "Camerún" },
    { value: "Canadá", displayValue: "Canadá" },
    { value: "Chad", displayValue: "Chad" },
    { value: "Chile", displayValue: "Chile" },
    { value: "China", displayValue: "China" },
    { value: "Chipre", displayValue: "Chipre" },
    { value: "Ciudad del Vaticano", displayValue: "Ciudad del Vaticano" },
    { value: "Colombia", displayValue: "Colombia" },
    { value: "Comores", displayValue: "Comores" },
    { value: "Congo", displayValue: "Congo" },
    { value: "Congo, República Democrática del", displayValue: "Congo, República Democrática del" },
    { value: "Corea del Sur", displayValue: "Corea del Sur" },
    { value: "Corea del Norte", displayValue: "Corea del Norte" },
    { value: "Costa de Marfíl", displayValue: "Costa de Marfíl" },
    { value: "Costa Rica", displayValue: "Costa Rica" },
    { value: "Coacria", displayValue: "Coacria (Hrvatska)" },
    { value: "Cuba", displayValue: "Cuba" },
    { value: "Dinamarca", displayValue: "Dinamarca" },
    { value: "Djibouti", displayValue: "Djibouti" },
    { value: "Dominica", displayValue: "Dominica" },
    { value: "Ecuador", displayValue: "Ecuador" },
    { value: "Egipto", displayValue: "Egipto" },
    { value: "El Salvador", displayValue: "El Salvador" },
    { value: "Emiratos Árabes Unidos", displayValue: "Emiratos Árabes Unidos" },
    { value: "Eritrea", displayValue: "Eritrea" },
    { value: "Eslovenia", displayValue: "Eslovenia" },
    { value: "España", displayValue: "España" },
    { value: "Estados Unidos", displayValue: "Estados Unidos" },
    { value: "Estonia", displayValue: "Estonia" },
    { value: "Etiopía", displayValue: "Etiopía" },
    { value: "Fiji", displayValue: "Fiji" },
    { value: "Filipinas", displayValue: "Filipinas" },
    { value: "Finlandia", displayValue: "Finlandia" },
    { value: "Francia", displayValue: "Francia" },
    { value: "Gabón", displayValue: "Gabón" },
    { value: "Gambia", displayValue: "Gambia" },
    { value: "Georgia", displayValue: "Georgia" },
    { value: "Ghana", displayValue: "Ghana" },
    { value: "Gibraltar", displayValue: "Gibraltar" },
    { value: "Granada", displayValue: "Granada" },
    { value: "Grecia", displayValue: "Grecia" },
    { value: "Groenlandia", displayValue: "Groenlandia" },
    { value: "Guadalupe", displayValue: "Guadalupe" },
    { value: "Guam", displayValue: "Guam" },
    { value: "Guatemala", displayValue: "Guatemala" },
    { value: "Guayana", displayValue: "Guayana" },
    { value: "Guayana Francesa", displayValue: "Guayana Francesa" },
    { value: "Guinea", displayValue: "Guinea" },
    { value: "Guinea Ecuatorial", displayValue: "Guinea Ecuatorial" },
    { value: "Guinea-Bissau", displayValue: "Guinea-Bissau" },
    { value: "Haití", displayValue: "Haití" },
    { value: "Honduras", displayValue: "Honduras" },
    { value: "Hungría", displayValue: "Hungría" },
    { value: "India", displayValue: "India" },
    { value: "Indonesia", displayValue: "Indonesia" },
    { value: "Irak", displayValue: "Irak" },
    { value: "Irán", displayValue: "Irán" },
    { value: "Irlanda", displayValue: "Irlanda" },
    { value: "Isla Bouvet", displayValue: "Isla Bouvet" },
    { value: "Isla de Christmas", displayValue: "Isla de Christmas" },
    { value: "Islandia", displayValue: "Islandia" },
    { value: "Islas Caimán" , displayValue: "Islas Caimán" },
    { value: "Islas Cook", displayValue: "Islas Cook" },
    { value: "Islas de Cocos o Keeling", displayValue: "Islas de Cocos o Keeling" },
    { value: "Islas Faroe", displayValue: "Islas Faroe" },
    { value: "Islas Heard y McDonald", displayValue: "Islas Heard y McDonald" },
    { value: "Islas Malvinas", displayValue: "Islas Malvinas" },
    { value: "Islas Marianas del Norte", displayValue: "Islas Marianas del Norte" },
    { value: "Islas Marshall", displayValue: "Islas Marshall" },
    { value: "Islas menores de Estados Unidos", displayValue: "Islas menores de Estados Unidos" },
    { value: "Islas Palau", displayValue: "Islas Palau" },
    { value: "Islas Salomón" , displayValue: "Islas Salomón" },
    { value: "Islas Svalbard y Jan Mayen", displayValue: "Islas Svalbard y Jan Mayen" },
    { value: "Islas Tokelau", displayValue: "Islas Tokelau" },
    { value: "Islas Turks y Caicos", displayValue: "Islas Turks y Caicos" },
    { value: "Islas Vírgenes (EEUU)", displayValue: "Islas Vírgenes (EEUU)" },
    { value: "Islas Vírgenes (Reino Unido)", displayValue: "Islas Vírgenes (Reino Unido)" },
    { value: "Islas Wallis y Futuna", displayValue: "Islas Wallis y Futuna" },
    { value: "Israel", displayValue: "Israel" },
    { value: "Italia", displayValue: "Italia" },
    { value: "Jamaica", displayValue: "Jamaica" },
    { value: "Japón", displayValue: "Japón" },
    { value: "Jordania", displayValue: "Jordania" },
    { value: "Kazajistán", displayValue: "Kazajistán" },
    { value: "Kenia", displayValue: "Kenia" },
    { value: "Kirguizistán", displayValue: "Kirguizistán" },
    { value: "Kiribati", displayValue: "Kiribati" },
    { value: "Kuwait", displayValue: "Kuwait" },
    { value: "Laos", displayValue: "Laos" },
    { value: "Lesotho", displayValue: "Lesotho" },
    { value: "Letonia", displayValue: "Letonia" },
    { value: "Líbano", displayValue: "Líbano" },
    { value: "Liberia", displayValue: "Liberia" },
    { value: "Libia", displayValue: "Libia" },
    { value: "Liechtenstein", displayValue: "Liechtenstein" },
    { value: "Lituania", displayValue: "Lituania" },
    { value: "Luxemburgo", displayValue: "Luxemburgo" },
    { value: "Macedonia", displayValue: "Macedonia, Ex-República Yugoslava de" },
    { value: "Madagascar", displayValue: "Madagascar" },
    { value: "Malasia", displayValue: "Malasia" },
    { value: "Malawi", displayValue: "Malawi" },
    { value: "Maldivas", displayValue: "Maldivas" },
    { value: "Malí", displayValue: "Malí" },
    { value: "Malta", displayValue: "Malta" },
    { value: "Marruecos", displayValue: "Marruecos" },
    { value: "Martinica", displayValue: "Martinica" },
    { value: "Mauricio", displayValue: "Mauricio" },
    { value: "Mauritania", displayValue: "Mauritania" },
    { value: "Mayotte", displayValue: "Mayotte" },
    { value: "México", displayValue: "México" },
    { value: "Micronesia", displayValue: "Micronesia" },
    { value: "Moldavia", displayValue: "Moldavia" },
    { value: "Mónaco", displayValue: "Mónaco" },
    { value: "Mongolia", displayValue: "Mongolia" },
    { value: "Montserrat", displayValue: "Montserrat" },
    { value: "Mozambique", displayValue: "Mozambique" },
    { value: "Namibia", displayValue: "Namibia" },
    { value: "Nauru", displayValue: "Nauru" },
    { value: "Nepal", displayValue: "Nepal" },
    { value: "Nicaragua", displayValue: "Nicaragua" },
    { value: "Níger", displayValue: "Níger" },
    { value: "Nigeria", displayValue: "Nigeria" },
    { value: "Niue", displayValue: "Niue" },
    { value: "Norfolk", displayValue: "Norfolk" },
    { value: "Noruega", displayValue: "Noruega" },
    { value: "Nueva Caledonia", displayValue: "Nueva Caledonia" },
    { value: "Nueva Zelanda", displayValue: "Nueva Zelanda" },
    { value: "Omán", displayValue: "Omán" },
    { value: "Países Bajos", displayValue: "Países Bajos" },
    { value: "Panamá", displayValue: "Panamá" },
    { value: "Papúa Nueva Guinea", displayValue: "Papúa Nueva Guinea" },
    { value: "Paquistán", displayValue: "Paquistán" },
    { value: "Paraguay", displayValue: "Paraguay" },
    { value: "Perú", displayValue: "Perú" },
    { value: "Pitcairn", displayValue: "Pitcairn" },
    { value: "Polinesia Francesa", displayValue: "Polinesia Francesa" },
    { value: "Polonia", displayValue: "Polonia" },
    { value: "Portugal", displayValue: "Portugal" },
    { value: "Puerto Rico", displayValue: "Puerto Rico" },
    { value: "Qatar", displayValue: "Qatar" },
    { value: "Reino Unido", displayValue: "Reino Unido" },
    { value: "República Centroafricana" , displayValue: "República Centroafricana" },
    { value: "República Checa", displayValue: "República Checa" },
    { value: "República Dominicana", displayValue: "República Dominicana" },
    { value: "República Eslovaca", displayValue: "República Eslovaca" },
    { value: "Reunión", displayValue: "Reunión" },
    { value: "Ruanda", displayValue: "Ruanda" },
    { value: "Rumania", displayValue: "Rumania" },
    { value: "Rusia", displayValue: "Rusia" },
    { value: "Sahara Occidental", displayValue: "Sahara Occidental" },
    { value: "Saint Kitts y Nevis", displayValue: "Saint Kitts y Nevis" },
    { value: "Samoa", displayValue: "Samoa" },
    { value: "Samoa Americana", displayValue: "Samoa Americana" },
    { value: "San Marino", displayValue: "San Marino" },
    { value: "San Vicente y Granadinas", displayValue: "San Vicente y Granadinas" },
    { value: "Santa Helena", displayValue: "Santa Helena" },
    { value: "Santa Lucía", displayValue: "Santa Lucía" },
    { value: "Santo Tomé y Príncipe", displayValue: "Santo Tomé y Príncipe" },
    { value: "Senegal", displayValue: "Senegal" },
    { value: "Seychelles" , displayValue: "Seychelles" },
    { value: "Sierra Leona", displayValue: "Sierra Leona" },
    { value: "Singapur", displayValue: "Singapur" },
    { value: "Siria", displayValue: "Siria" },
    { value: "Somalia", displayValue: "Somalia" },
    { value: "Sri Lanka", displayValue: "Sri Lanka" },
    { value: "St Pierre y Miquelon", displayValue: "St Pierre y Miquelon" },
    { value: "Suazilandia", displayValue: "Suazilandia" },
    { value: "Sudáfrica", displayValue: "Sudáfrica" },
    { value: "Sudán", displayValue: "Sudán" },
    { value: "Suecia", displayValue: "Suecia" },
    { value: "Suiza", displayValue: "Suiza" },
    { value: "Surinam", displayValue: "Surinam" },
    { value: "Tailandia", displayValue: "Tailandia" },
    { value: "Taiwán", displayValue: "Taiwán" },
    { value: "Tanzania", displayValue: "Tanzania" },
    { value: "Tayikistán", displayValue: "Tayikistán" },
    { value: "Territorios franceses del Sur", displayValue: "Territorios franceses del Sur" },
    { value: "Timor Oriental", displayValue: "Timor Oriental" },
    { value: "Togo", displayValue: "Togo" },
    { value: "Tonga", displayValue: "Tonga" },
    { value: "Trinidad y Tobago", displayValue: "Trinidad y Tobago" },
    { value: "Túnez", displayValue: "Túnez" },
    { value: "Turkmenistán", displayValue: "Turkmenistán" },
    { value: "Turquía", displayValue: "Turquía" },
    { value: "Tuvalu", displayValue: "Tuvalu" },
    { value: "Ucrania", displayValue: "Ucrania" },
    { value: "Uganda", displayValue: "Uganda" },
    { value: "Uruguay", displayValue: "Uruguay" },
    { value: "Uzbekistán", displayValue: "Uzbekistán" },
    { value: "Vanuatu", displayValue: "Vanuatu" },
    { value: "Venezuela", displayValue: "Venezuela" },
    { value: "Vietnam", displayValue: "Vietnam" },
    { value: "Yemen", displayValue: "Yemen" },
    { value: "Yugoslavia", displayValue: "Yugoslavia" },
    { value: "Zambia", displayValue: "Zambia" },
    { value: "Zimbabue", displayValue: "Zimbabue" }
]