//Auth actions

export const FETCH_AUTH = "FETCH_AUTH";
export const LOGOUT_SUCCESS = 'LOGOUT';
export const LOGIN_SUCCESS = "LOGIN";
export const LOGIN_FAILED = "LOGIN_FAILED"; 

// Messages actions

export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES";
export const FETCH_MESSAGES_FAILED = "FETCH_MESSAGES_FAILED";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const READ_MESSAGE = "READ_MESSAGE";
export const RESET_STATUS_MESSAGE = "RESET_STATUS_MESSAGE"; 

//Destination actions

export const SET_SELECTED_DESTINATION = "SET_SELECTED_DESTINATION";
export const RESET_SELECTED_DESTINATION = "RESET_SELECTED_DESTINATION";
export const UPDATE_SELECTED_DESTINATION_GALLERY = "UPDATE_SELECTED_DESTINATION_GALLERY";